groups:
  webpack:
    dependencies:
      webpack: ^5.95.0
      webpack-cli: ^5.1.4
      ts-loader: ^9.5.1
      react: ^18.2.0
      react-dom: ^18.2.0
      react-router-dom: ^6.20.0
    devDependencies:
      "@types/webpack": ^5.28.0
      "@types/react": ^18.2.0
      "@types/react-dom": ^18.2.0
  vue:
    dependencies:
      vue: ^3.5.17
    devDependencies:
      "@vue/compiler-sfc": ^3.5.17
      "@vitejs/plugin-vue": ^5.0.0
      "@vitest/ui": ^1.0.0
      vite: ^5.0.0
      vitest: ^1.0.0
  react:
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0
      react-router-dom: ^6.20.0
      ts-loader: ^9.5.1
      webpack: ^5.95.0
      webpack-cli: ^5.1.4
    devDependencies:
      "@types/react": ^18.2.0
      "@types/react-dom": ^18.2.0
      "@types/webpack": ^5.28.0
  vite:
    devDependencies:
      vite: ^5.0.0
      "@vitejs/plugin-vue": ^5.0.0
      "@vitest/ui": ^1.0.0
      "@vue/compiler-sfc": ^3.5.17
      vitest: ^1.0.0
    dependencies:
      vue: ^3.5.17
  testing:
    devDependencies:
      vitest: ^1.0.0
      "@vitest/ui": ^1.0.0
      "@vitejs/plugin-vue": ^5.0.0
      "@vue/compiler-sfc": ^3.5.17
      vite: ^5.0.0
    dependencies:
      vue: ^3.5.17
